### ISSUE TITLE
惊喜发现有第三方，但可惜手机带不动

### ISSUE THREAD

**Issue by Bianca2000** [Robert-Stackflow/Loftify#1]
目前手機使用android10，遇到如下問題：
1. 登入後"我的"介面顯示異常
2. 試著點讚後回到原LOFTER APP可以看到沒有點上讚
3. 點進文章頁面呈現空白
4. 下載桌面版只在後台運行無法看見視窗
5. 綜上所述基本無法使用

**Comment by Robert-Stackflow** [comment]
能提供更多資訊嗎？
1.登入後，我的頁面顯示仍未登入？
2.可能是未登入成功，你使用的是什麼登入方式（驗證碼登入、手機號密碼登入、Lofter ID 登入）？你的手機號是 +86 嗎？
3.所有文章頁面都會顯示空白嗎？可否提供一篇文章（提供標題或者作者名稱都可以）？
4.你的 Windows 版本資訊是什麼？

**Comment by Bianca2000** [comment]
我試著用手機錄了一下
[錄屏](https://i.ibb.co/3mtSVrr/1.gif)
windows我試過win10 跟win11都不能顯示視窗

**Comment by Robert-Stackflow** [comment]
抱歉，我暫時無法準確定位問題。 過段時間後，我將會發佈一個新版本，包含日誌匯出功能。 請您在新版本的設定中匯出日誌，並發送到我的郵箱 yutuan.victory@gmail.com ，方便我查找問題，感謝！
