### ISSUE TITLE
可以添加看彩蛋的功能吗

### ISSUE THREAD

**Issue by zeswa** [Robert-Stackflow/Loftify#2]
特别特别好用！感觉直接可以卸载官方了就是没法看彩蛋现在好多文几乎都放彩蛋里，希望作者考虑一下！

**Comment by Robert-Stackflow** [comment]
感谢你的支持！但是受限于官方接口，无法实现查看彩蛋的功能；同时这涉及到版权和法律风险，未来不会实现
