### ISSUE TITLE
自定义的下载路径没用

### ISSUE THREAD

**Issue by zwmopen** [Robert-Stackflow/Loftify#3]
测试OPPOR11
红米Note8
小米9A

都是下载路径自定义了，但是都下载再根目录下的PIcture里面了。

**Comment by Robert-Stackflow** [comment]
请你下载[临时版本](https://github.com/Robert-Stackflow/Loftify/actions/runs/11652579768/artifacts/2138086049)查看是否可以正常保存至自定义下载路径

你将下载得到一个ZIP压缩文件，解压后根据你的abi版本选择安装并测试

**Comment by Robert-Stackflow** [comment]
请你检查2.3.0版本能否正常工作
